### ISSUE TITLE
unknown log

### ISSUE THREAD

**Issue by ganico** [AgoraIO/AgoraRtcEngine_iOS#11]
hi, previously we're using old version of agora and now we updated into 3.5.1, I noticed that when user joins the room i'm seeing this logs:

Support FP16!
Not support dotproduct!
Not support SVE!

any idea about it? I also attached screenshot.
<img width="779" alt="Screen Shot 2021-11-26 at 5 47 53 PM" src="https://user-images.githubusercontent.com/7714293/143561299-5b1a01dc-a726-40cc-8199-ea76d11a57c2.png">

**Comment by maxxfrazer** [comment]
I've asked the SDK team about this too, seems harmless, but I'll report back here if I can get some clarity
