### ISSUE TITLE
Mute Local Audio Stream Unexpected Behavior 

### ISSUE THREAD

**Issue by rrozenv** [AgoraIO/AgoraRtcEngine_iOS#12]
## Objective 
Mute the users local audio stream so that it is not published to the channel and use `AVAudioRecorder` to detect the users speaking volume locally. 

## Issue
Calling [`muteLocalAudioStream(true)` ](https://docs.agora.io/en/Voice/API%20Reference/oc/Classes/AgoraRtcEngineKit.html#//api/name/muteLocalAudioStream:)successfully stops publishing the audio stream to the channel, but `AVAudioRecorder` stops receiving local audio data which is unexpected. In the documentation it states:
-  As of v3.4.5, this method only sets the publishing status of the audio stream in the channel of AgoraRtcEngineKit
- This method does not change the usage status of the audio-capturing device. 

However this is not the observed behavior. Calling `muteLocalAudioStream(true)` seems to disable the devices microphone access. 

## Code
The objective of the code below is to start recording a users local audio using `AVAudioRecorder` after the current user joins a channel. 
```
public class _AgoraClient: NSObject, AgoraRtcEngineDelegate {
    private let appId: String
    private let recorderUrl: URL
    
    private var agora: AgoraRtcEngineKit!
    private var recorder: AVAudioRecorder?
    private var timer: Timer?
   
    public init(appId: String) {
        self.appId = appId
        self.recorderUrl = FileManager.default
            .urls(for: .documentDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("local_volume.m4a")
        super.init()
        
        agora = AgoraRtcEngineKit.sharedEngine(withAppId: appId, delegate: self)
    }
    
    deinit {
        leave()
        agora = nil
        stopRecorder()
        AgoraRtcEngineKit.destroy()
    }
    
    // MARK: AgoraRtcEngineDelegate

    public func rtcEngine(_ engine: AgoraRtcEngineKit, didLeaveChannelWith stats: AgoraChannelStats) {
        stopRecorder()
    }
    
    // MARK: Agora

    func join(uid: UInt, channel: String, token: String, muted: Bool, forceMuted: Bool, volume: Bool) {
        agora.joinChannel(byToken: token, channelId: channel, info: nil, uid: uid) { [weak self] _ in
            self?.agora.enableLocalAudio(true)
            self?.startRecorder()
        }
    }

    func leave() {
        agora.leaveChannel(nil)
    }

    func setMute(shouldMute: Bool) {
        print("MUTE AGORA: \(shouldMute)")
        agora.muteLocalAudioStream(shouldMute)
    }
    
    // MARK: AVAudioRecorder

    func startRecorder() {
        let settings = [
            AVFormatIDKey: Int(kAudioFormatMPEG4AAC),
            AVSampleRateKey: 12000,
            AVNumberOfChannelsKey: 1,
            AVEncoderAudioQualityKey: AVAudioQuality.high.rawValue
        ]
        
        do {
            let session = AVAudioSession.sharedInstance()
            try session.setCategory(.playAndRecord, options: .mixWithOthers)
            try session.setActive(true)
            
            let recorder = try AVAudioRecorder(url: recorderUrl, settings: settings)
            recorder.isMeteringEnabled = true
            recorder.prepareToRecord()
            recorder.record()
            
            let timer = Timer.scheduledTimer(withTimeInterval: 1, repeats: true, block: { _ in
                recorder.updateMeters()
                let volume = Int(recorder.averagePower(forChannel: 0))
                print("RECORDER - volume \(volume)")
            })
            
            self.recorder = recorder
            self.timer = timer
            
            print("RECORDER - started")
        } catch {
            print(error)
        }
    }
    
    func stopRecorder() {
        timer?.invalidate()
        recorder?.stop()
        recorder?.deleteRecording()
        recorder = nil
        print("RECORDER - stopped")
    }
}
```
## Output
1. After joining the channel and starting the recorder the volume measured using `AVAudioRecorder` prints the correct volume levels.
2. When `agora.muteLocalAudioStream(true)` is called the volume measured using `AVAudioRecorder` starts emitting -120 which is not expected. 
3. When `agora.muteLocalAudioStream(false)` is called the volume measured using `AVAudioRecorder` starts printing the correct volume levels again.
```
RECORDER - started
RECORDER - volume -63
RECORDER - volume -61
RECORDER - volume -64
RECORDER - volume -46
RECORDER - volume -64
RECORDER - volume -34
RECORDER - volume -41
RECORDER - volume -14
RECORDER - volume -51
RECORDER - volume -67
RECORDER - volume -67
MUTE AGORA: true
RECORDER - volume -91
RECORDER - volume -120
RECORDER - volume -120
RECORDER - volume -120
RECORDER - volume -120
RECORDER - volume -120
RECORDER - volume -120
RECORDER - volume -120
RECORDER - volume -120
RECORDER - volume -120
RECORDER - volume -120
RECORDER - volume -120
MUTE AGORA: false
RECORDER - volume -62
RECORDER - volume -66
RECORDER - volume -11
RECORDER - volume -9
RECORDER - volume -47
RECORDER - volume -43
RECORDER - volume -68
RECORDER - volume -66
RECORDER - volume -72
RECORDER - volume -60
RECORDER - volume -69
RECORDER - volume -70
```
## Questions
Am I misinterpreting the documentation and this is actually the expected behavior? 

If so, then what is the difference between `enableLocalAudio` vs. `muteLocalAudioStream`? 

Is there another approach I should look into to achieve the stated objective?

**Comment by maxxfrazer** [comment]
Hi @rrozenv 👋

Thank you so much for having a good level of content in your ticket first of all!
This repo is for distributing the SDK, and for opening issues with compatibility or Swift PM installation related issues.

Could you copy the content from this issue to a ticket via the support page? Click support form the top bar on console.agora.io, or follow [this link](https://agora-ticket.agora.io) to get there.

They should be able to give you a detailed answer of what actually happens to the microphone when calling `muteLocalAudioStream`.
