### ISSUE TITLE
Failed to install using SPM

### ISSUE THREAD

**Issue by ppokalnis** [AgoraIO/AgoraRtcEngine_iOS#15]
Hello, today we've started to see the problem with installing your lib via Swift Package Manager.
It hangs out on the following screen and blocks several teammates to build our Xcode project.

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/97443762/157917163-7fa7ed86-e5d0-4e24-9fef-0dfc17610dab.png">

"Reset Package Caches"  doesn't help.
Installing on empty project has the same problem.
Installing previous versions has the same problem.

Looks like your lib binary is unavailable.
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/97443762/157920532-d20e80aa-ee16-45c1-9ba5-e5fae3e3eeec.png">

Thanks in advance for any advices how to resolve/bypass this.

**Comment by maxxfrazer** [comment]
Hi @ppokalnis, I just tried installing and didn't have an issue, as well as the following referenced link in the error message above does not have an issue with download:
https://download.agora.io/swiftpm/AgoraRtcEngine_iOS/3.6.2/AgoraRtcKit.xcframework.zip

You're also targeting the main branch for the clone. Please don't do that, sometimes we update the main branch with an update to an older version: with this package and every other package it's better to target by versions.

It seems like a common SwiftPM issue people have. Here's some solutions on a thread at Firebase's package with similar symptoms:
Manually clearing cache: https://github.com/firebase/firebase-ios-sdk/issues/8812#issuecomment-944611411
Slightly less nice manual download and inserting the package: https://github.com/firebase/firebase-ios-sdk/issues/8812#issuecomment-955186000

**Comment by ppokalnis** [comment]
Hi @maxxfrazer 
Thank you for your feedback. 
This morning I've managed to fetch this lib. We will keep an eye on this.
