### ISSUE TITLE
 'AgoraRtcEngine_iOS 3.4.6'======= AgoraLiveManager.destroyAgoraEngine(_:) crash

### ISSUE THREAD

**Issue by 405092901** [AgoraIO/AgoraRtcEngine_iOS#17]
pod 'AgoraRtcEngine_iOS', '3.4.6'

it is crash log，fix it crash as soon as possible please

Incident Identifier: 26E3AC45-0652-4AD4-90AD-47A23066D12E
Hardware Model:      iPhone9,3
Process:             Xxxxx [4467]
Path:                /private/var/containers/Bundle/Application/87D8A3F0-7485-4D7E-9DA6-90212FC35208/Xxxxx.app/Xxxxx
Identifier:          XXXX
Version:             4.6.0 (3691)
AppStoreTools:       13F15
AppVariant:          1:iPhone9,3:15
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           XXXX [722]

Date/Time:           2022-05-25 00:29:45.5173 +0530
Launch Time:         2022-05-25 00:25:49.6514 +0530
OS Version:          iPhone OS 15.3.1 (19D52)
Release Type:        User
Baseband Version:    6.01.01
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: FRONTBOARD 2343432205 
<RBSTerminateContext| domain:10 code:0x8BADF00D explanation:[application<XXXX>:4467] failed to terminate gracefully after 5.0s
ProcessVisibility: Unknown
ProcessState: Running
WatchdogEvent: process-exit
WatchdogVisibility: Background
WatchdogCPUStatistics: (
"Elapsed total CPU time (seconds): 22.100 (user 22.100, system 0.000), 100% CPU",
"Elapsed application CPU time (seconds): 1.069, 5% CPU"
) reportType:CrashLog maxTerminationResistance:Interactive>

Triggered by Thread:  0

Thread 0 name:
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001bb7754f0 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	0x00000001dbc9bbfc _pthread_cond_wait$VARIANT$mp + 1216 (pthread_cond.c:636)
2   AgoraCore                     	0x000000010c09b9d0 0x10c090000 + 47568
3   AgoraCore                     	0x000000010c09ba8c 0x10c090000 + 47756
4   AgoraCore                     	0x000000010c09bc1c ahpl_main_exit_wait + 28
5   AgoraRtcKit                   	0x000000010c44bfe8 agora::base::IAgoraService::release() + 48
6   AgoraRtcKit                   	0x000000010c4e3b08 0x10c1d4000 + 3209992
7   Xxxxx                          	0x0000000107b81030 AgoraLiveManager.destroyAgoraEngine(_:) + 228 (AgoraLiveManager.swift:657)
8   Xxxxx                          	0x00000001078de4cc LiveAgoraPusher.destroyEngine() + 92 (LiveAgoraPusher.swift:240)
9   Xxxxx                          	0x00000001078df71c protocol witness for XxxxxLivePusher.destroyEngine() in conformance LiveAgoraPusher + 36 (<compiler-generated>:0)
10  Xxxxx                          	0x0000000105dc61bc BroadcastController.destoryAgoraLiveManager(ignoreVoiceDevice:) + 560 (BroadcastController.swift:3448)
11  Xxxxx                          	0x0000000105db8fa0 BroadcastController.stopBroadcast(reason:_:) + 688 (BroadcastController.swift:3972)
12  Xxxxx                          	0x0000000105d73af8 BroadcastController.progressStopBroadcast(breaked:reasonCode:reason:tostText:) + 508 (BroadcastController.swift:3779)
13  Xxxxx                          	0x0000000105da1924 0x104b28000 + 19372324
14  Xxxxx                          	0x0000000105dcbb04 closure #1 in BroadcastController.confirmStopBroadcast() + 156 (BroadcastController.swift:3751)
15  Xxxxx                          	0x0000000106a2429c 0x104b28000 + 32490140
16  UIKitCore                     	0x0000000183a69510 -[UIAlertController _invokeHandlersForAction:] + 108 (UIAlertController.m:1219)
17  UIKitCore                     	0x000000018400cfdc __103-[UIAlertController _dismissAnimated:triggeringAction:triggeredByPopoverDimmingView:dismissCompletion:]_block_invoke.454 + 28 (UIAlertController.m:1384)
18  UIKitCore                     	0x0000000183cab854 -[UIPresentationController transitionDidFinish:] + 1256 (UIPresentationController.m:521)
19  UIKitCore                     	0x00000001841b6ff0 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.437 + 208 (UIPresentationController.m:1193)
20  UIKitCore                     	0x0000000183b4fd08 -[_UIViewControllerTransitionContext completeTransition:] + 112 (UIViewControllerTransitioning.m:289)
21  UIKitCore                     	0x0000000183bcf61c -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:] + 688 (UIView.m:14898)
22  UIKitCore                     	0x0000000183aa3478 -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 244 (UIView.m:0)
23  UIKitCore                     	0x0000000183ab6d68 -[UIViewAnimationState animationDidStop:finished:] + 240 (UIView.m:2280)
24  UIKitCore                     	0x0000000183ab6ebc -[UIViewAnimationState animationDidStop:finished:] + 580 (UIView.m:2299)
25  QuartzCore                    	0x0000000185195e64 CA::Layer::run_animation_callbacks(void*) + 276 (CALayer.mm:7203)
26  libdispatch.dylib             	0x000000018131b1a8 _dispatch_client_callout + 16 (object.m:560)
27  libdispatch.dylib             	0x00000001812c75e0 _dispatch_main_queue_callback_4CF$VARIANT$mp + 940 (inline_internal.h:2601)
28  CoreFoundation                	0x000000018160a888 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12 (CFRunLoop.c:1795)
29  CoreFoundation                	0x00000001815c8188 __CFRunLoopRun + 2528 (CFRunLoop.c:3144)
30  CoreFoundation                	0x00000001815dae1c CFRunLoopRunSpecific + 572 (CFRunLoop.c:3268)
31  GraphicsServices              	0x00000001a197d9a0 GSEventRunModal + 160 (GSEvent.c:2200)
32  UIKitCore                     	0x0000000183e0eb90 -[UIApplication _run] + 1080 (UIApplication.m:3493)
33  UIKitCore                     	0x0000000183ba416c UIApplicationMain + 332 (UIApplication.m:5047)
34  Xxxxx                          	0x0000000104d2cd50 0x104b28000 + 2116944
35  dyld                          	0x000000010bd3c250 start + 444 (dyldMain.cpp:879)

**Comment by maxxfrazer** [comment]
Looks like you're using CocoaPods (this repo is for swift package manager installation), and on an old version 3.4.6. Do you get these issues with the latest version?

**Comment by maxxfrazer** [comment]
Going to close this issue, please let us know if there's an issue using the latest SDK version via the support page (found on console.agora.io)
