### ISSUE TITLE
XCFramework binary size too big

### ISSUE THREAD

**Issue by TheCoordinator** [AgoraIO/AgoraRtcEngine_iOS#18]
Hey all,

Are there any plans to reduce the binary frameworks' size? It seems to me the sizes are way too large. 

Currently seeing AgoraRTCKit at `~430MB` and BeQuic at `130MB`.

Thanks.

**Comment by plutoless** [comment]
@TheCoordinator  i think the reason is it includes sdk for all arch. does it increase your final app product a lot as well? i believe not all files will be linked when building release app.

**Comment by TheCoordinator** [comment]
Hi @plutoless, yes you are spot on. However when looking at the AppStore bundle size on my device (iPhone 11 Pro) my app size has indeed been increased by 40MB which I still would say is quite a lot. Obviously don't know what the absolute must have dependencies are. But this is still quite big. Wondering if there's a way I can reduce this given my use-case? i.e. only link dependencies that I need via a custom package?

**Comment by plutoless** [comment]
@TheCoordinator 
the baseline is media sdk will be a lot more bigger than normal sdk mainly due to its complicated dependencies (e.g. decoder codec/encoder codec etc) so 40mb increase does not sound too surprising to me.
the chances are: 
1. see if you are using audio-only features. if you don't need video, this will be a big advantage when you want to reduce your app size. In this case you can choose to use our audio sdk, which is basically a slim sdk version which removes video modules.
2. for some advanced features (like beauty), we have designed to make these features into separate dynamic libraries. if you are not using these features, you can choose to not link them in xode, which may also help you in this case.

**Comment by TheCoordinator** [comment]
Thanks for that @plutoless.

I am using liveBroadcasting mode so would need both video/audio and nothing fancy at all.

What libs do you recommend me to drop from this list here so I make sure, I don't break anything.

https://github.com/agorabuilder/AgoraRtcEngine_iOS_Beta/blob/master/Package.swift

**Comment by plutoless** [comment]
@TheCoordinator 
this page should solve your concern,
https://docs.agora.io/en/Video/reduce_rtc_app_size?platform=iOS

**Comment by TheCoordinator** [comment]
OK thanks @plutoless. 

Not sure if removing the extensions will change dramatically but will give it a go anyway. In the long run, do you have any plans to reduce the video framework size?

**Comment by maxxfrazer** [comment]
Not in the pipeline for now. We'll raise it internally to see if a lightweight version could be possible in the future, as there's many benefits to that.

**Comment by TheCoordinator** [comment]
Thank you @maxxfrazer That'll be hugely benefitial.

**Comment by TheCoordinator** [comment]
Hey @maxxfrazer , Thanks for the update. See there's been some changes since the beta on how products can be linked via SPM. Is this issue now resolved if I use `RtcBasic`?

**Comment by TheCoordinator** [comment]
Which I assume, it means I can use the bare minimum and none of the extensions.

**Comment by maxxfrazer** [comment]
you’re correct @TheCoordinator, we’ll update the README here to make that clearer. the other packages are for various things like background segmentation.
The largest package product, AgoraRtcKit, is still included in RtcBasic though, so won’t solve everything in terms of size.

**Comment by TheCoordinator** [comment]
Thanks @maxxfrazer, I think this is already an improvement. I had 20MB back just by this change and removing unnecessary extensions compared to the last beta. 👏🏼 

But you're right, it'd be great if we can also have a more basic version of AgoraRtcKit in the future updates.

**Comment by maxxfrazer** [comment]
also each xcframework contains multiple architectures - at least 1 for the physical device, and 2 for the simulator. only one will actually be bundled when it goes to a device.

they really add up when in the xcframework format..!

**Comment by TheCoordinator** [comment]
Obviously xcframework itself is not a huge issue, as discussed above what gets linked based on the arch is important. If there are room for more improvement over that, it'd be highly appreciated.

**Comment by maxxfrazer** [comment]
@TheCoordinator I believe we've made some huge progress on reducing the app size. The XCFramework for the core SDK (those included in RtcBasic).

**Comment by TheCoordinator** [comment]
> @TheCoordinator I believe we've made some huge progress on reducing the app size. The XCFramework for the core SDK (those included in RtcBasic).

Great to hear @maxxfrazer. Will give it a go for our next version.

**Comment by maxxfrazer** [comment]
Going to assume it's better now, please re-open if you're still facing the issue.
