### ISSUE TITLE
setLocalRenderMode doesn't work correctly.

### ISSUE THREAD

**Issue by canbalkaya** [AgoraIO/AgoraRtcEngine_iOS#20]
I tried to use setLocalRenderMode method to use mirror feature, because set setLocalVideoMirrorMode method has got deprecated. Unfortunately, I got errors like "Incorrect argument label in call" from Xcode. setLocalRenderMode's parameters have a problem.
<img width="999" alt="Screen Shot 2022-07-28 at 1 38 14 14PM" src="https://user-images.githubusercontent.com/18351145/181486184-11837d68-f8df-46ab-8468-dbfff4be3785.png">

<img width="999" alt="Screen Shot 2022-07-28 at 1 38 45 45PM" src="https://user-images.githubusercontent.com/18351145/181486202-28eab476-b436-4340-be92-557a05312285.png">

**Comment by plutoless** [comment]
@canbalkaya which version of sdk are you using?

**Comment by canbalkaya** [comment]
3.7.0

**Comment by plutoless** [comment]
@canbalkaya try doing it like this
![image](https://user-images.githubusercontent.com/471561/181514846-50b8107b-d3ab-46ae-9b6b-02a854485b58.png)

**Comment by canbalkaya** [comment]
Yes, it works. Thank you.
