### ISSUE TITLE
AppID on client side

### ISSUE THREAD

**Issue by nitsanasraf** [AgoraIO/AgoraRtcEngine_iOS#22]
To initialize the agora kit engine I need to call this method on the client side:
`AgoraRtcEngineKit.sharedEngine(withAppId:  APP_ID, delegate: self)`
But what if I want to store my APP_ID on the server side, and not send it to the client side in order to protect my API keys?
Can it be achieved?

**Comment by plutoless** [comment]
of course. you can request from your server your appid and use that to initialize your rtc engine instance.
to achieve better security, take a look at here https://docs.agora.io/en/live-streaming-premium-legacy/token_server?platform=iOS

**Comment by nitsanasraf** [comment]
@plutoless yes that’s what I’m doing at the moment. The issue is that the endpoint on the server for requesting the appid could be compromise and this could lead to my keys being stolen, that’s why I was wondering if there’s a way to not need the appid at all at the client side which will reduce the risk of stealing my api keys

**Comment by plutoless** [comment]
as i mentioned above, you can use token approach which is more secure compared to appid approach

**Comment by nitsanasraf** [comment]
Oh sorry, didn’t catch that. 
thank you !
