### ISSUE TITLE
Difference between 2 methods of creating an AgoraRtcEngine?

### ISSUE THREAD

**Issue by nitsanasraf** [AgoraIO/AgoraRtcEngine_iOS#23]
What are the differences between creating an AgoraRtcEngineKit in this way:
`agoraKit = AgoraRtcEngineKit.sharedEngine(withAppId: APP_ID, delegate: self)
`
To this way:
`agoraKit = AgoraRtcEngineKit()`

The reason I am asking is that I want to avoid providing an APP_ID when creating an AgoraRtcEngine.

**Comment by maxxfrazer** [comment]
The initialiser without parameters isn't right - looks like it's just inherited from NSObject.

What's the objective of not providing an app id? If you don't want to provide a valid one, then an empty string could work just as well depending on what you're wanting to achieve.

**Comment by nitsanasraf** [comment]
@maxxfrazer I don’t want to provide an app Id to the client from security reasons.
I will try using an empty string and will update, thank you.

**Comment by nitsanasraf** [comment]
@maxxfrazer I provided an empty string, which seems to have no effect on the functionality of my app.
Why does the init requires an app id ? what the app id is used for in the init of the engine?

**Comment by plutoless** [comment]
@nitsanasraf 
short answer is no you can't initialize an engine without an appId.
the appropriate approach to protect your info is using token, which you can find relevant help docs here:
https://docs.agora.io/en/video-call-4.x/token_server_android_ng?platform=Android

if you want to stick to appId only anyway, you can use your server to send appId to client when user logs in, which, though, is still pretty insecure. token approach is recommended when you want proper level of security.

**Comment by nitsanasraf** [comment]
@plutoless Hi, some questions about that:
1. I've already implemented auth with tokens, but it seems it is only to protect functionalities within Agora. what I am talking about is just not using the app id in the front-end to prevent a client from retrieving my app id, regardless of Agora's framework, the only thing that prevents me from doing so, is the way I have to provide an app id in the init of the engine, so in that case, the app id must live in the frontend as well.
Ex, in the link you sent me:
`Agora uses digital tokens to authenticate users and their privileges before they access an Agora service, such as joining an Agora call or logging into the real-time messaging system.`

2. Why is my engine working properly with an empty string for the app_id argument? what issues could it cause if I keep it like that?
Ex.
`agoraKit = AgoraRtcEngineKit.sharedEngine(withAppId:"", delegate: self)`

**Comment by plutoless** [comment]
@nitsanasraf 
1. if you have implemented auth with tokens, having your appId being stolen by someone else will not do your any harm. Is there any concerns you have for your appid being stolen? as i mentioned if you don't want the appId to live in your static frontend code, you can use your server to dispatch the appId on the fly. but still if someone has the knowledge to intercept the network packets he can still get the appId. as long as the appId is static, there's always ways to get it.

2. i think giving an empty string only fixes the compile issues. You may get immediate error indicating invalid format of appid and there might be some more unexpected behaviors.

**Comment by nitsanasraf** [comment]
@plutoless Aha, I appreciate all the help!
I got one last question, so a token is made of: channel name,uid, appid, expiration time, and app certificate.
so what prevents him from generating his own token? he can use my appid, a random channel name and uid, and his app certificate.
Sorry for all the questions, just making sure I am not making any mistakes before proceeding to a paid account.

**Comment by plutoless** [comment]
only the combination of your appid and your certificate generates a correct token. certificate is usually stored on your server to sign tokens. so there's no way for others to steal it.
token generated with a combination of your appid and some other projects' certificate is not valid.

**Comment by nitsanasraf** [comment]
@plutoless Awesome, that's what I suspected.
Thank you so much for all the answers!
