### ISSUE TITLE
App Crash on Launch

### ISSUE THREAD

**Issue by ankit0812** [AgoraIO/AgoraRtcEngine_iOS#24]
Getting this error : 

dyld[30739]: Library not loaded: '@rpath/AgoraJNDExtension.framework/AgoraJNDExtension'
Library not loaded: '@rpath/AgoraJNDExtension.framework/AgoraJNDExtension'

**Comment by maxxfrazer** [comment]
What SDK version are you using there?

**Comment by ankit0812** [comment]
3.7.0.3

**Comment by ankit0812** [comment]
Not happening every time. This is intermittent.

**Comment by maxxfrazer** [comment]
If it happens again, please try `ping download.agora.io`. I'm seeing some devs not able to hit this URL.

**Comment by brightfuture** [comment]
same issue here
my crash message is on AgoraRtcKit.shareEngine init

**Comment by brightfuture** [comment]
crash happens on mine every time except the first installation

**Comment by brightfuture** [comment]
I think I found the issue 
my app is written in SwiftUI 
I'm initializing AgoraRtcKit.sharedEngine during the initalization of my first state object 
the crash doesn't happen when I set the property to lazy var
which means this has something to do with when the shared engine is initialized 
too early it crashes, a little later it's fine

**Comment by maxxfrazer** [comment]
thanks for the info @brightfuture, we’ll look into this and make sure it’s in the documentation.

**Comment by maxxfrazer** [comment]
Looks like this is sorted, closing issue!
