### ISSUE TITLE
Can't add Swift Package Manager(Now working)

### ISSUE THREAD

**Issue by sreymomtong** [AgoraIO/AgoraRtcEngine_iOS#25]
I have tried to add by Swift Package Manager, but i have error. And i try to install by pod install too. but it still doesn't work.
I use Xcode Version  13.4

![Screen Shot 2022-09-16 at 2 40 53 PM](https://user-images.githubusercontent.com/21187787/190584082-7d13db4e-6d77-439a-af3d-38015fe5f43a.png)
![Screen Shot 2022-09-16 at 2 24 04 PM](https://user-images.githubusercontent.com/21187787/190584092-410eddcd-dc05-4500-b361-b6745848c8ef.png)

**Comment by maxxfrazer** [comment]
Could you try this in terminal on the same machine? `ping download.agora.io`

I found another dev having issues hitting that URL.

**Comment by maxxfrazer** [comment]
Going to close this as it seems to be working for you. But if you have this issue again please let us know and see if you can ping that address.
