### ISSUE TITLE
Some warning when using the SPM package

### ISSUE THREAD

**Issue by JetForMe** [AgoraIO/AgoraRtcEngine_iOS#3]
Thanks for making this! We were finally able to dump Cocoapods.

There are a few warnings when using this package, should be easy to fix:

```
AgoraRtcKit.framework/Headers/AgoraRtcEngineKit.h:3340:35: Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
AgoraRtcKit.framework/Headers/AgoraRtcEngineKit.h:3340:35: Insert '_Nullable' if the pointer may be null
AgoraRtcKit.framework/Headers/AgoraRtcEngineKit.h:3340:35: Insert '_Nonnull' if the pointer should never be null

AgoraRtcKit.framework/Headers/AgoraRtcEngineKit.h:3593:67: Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
AgoraRtcKit.framework/Headers/AgoraRtcEngineKit.h:3593:67: Insert '_Nullable' if the pointer may be null
AgoraRtcKit.framework/Headers/AgoraRtcEngineKit.h:3593:67: Insert '_Nonnull' if the pointer should never be null
```

There's also this one (building with Xcode 13b1, not sure about 12.5.1):

```
AgoraRtcEngine_iOS/Package.swift The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99.
```

If you guys actually still support iOS 8.0, then I don't think there's much that can be done. But if you don't support iOS 8, then perhaps this can be changed?

Thanks!

**Comment by maxxfrazer** [comment]
Hi @JetForMe, thanks for using this swift package, makes integration so much nicer than cocoapods that's for sure!

The issues on this repo should be reserved for issues integrating the SDK through swiftPM, but the issues you're seeing are from the framework itself. Go ahead and open a ticket for the pointer nullability warnings if you have chance:
https://agora-ticket.agora.io

For iOS 8.0 it actually is supported for better or for worse, despite it running on <0.1% of devices now.

**Comment by JetForMe** [comment]
That link requires signup, that despite offering 3rd-party login through Github, still wants my phone number. I'd rather not.

**Comment by maxxfrazer** [comment]
I'm assuming you have an agora account?
Head to https://console.agora.io, then select "Support" along the top bar.
As you can see in the orange banner in this image I haven't added my phone number; it asks for a number but you don't need to add one
![Screenshot 2021-07-12 at 17 11 50](https://user-images.githubusercontent.com/5754073/125321179-56437c80-e334-11eb-9522-b3492b08a13a.png)

**Comment by JetForMe** [comment]
I don't think I do. Someone else at the company selected Agora long ago, I'm just a lowly iOS developer integrating it into our new app.

**Comment by maxxfrazer** [comment]
@JetForMe I just checked 3.4.6 (just released), it builds fine with this package on M1 simulator 🚀

**Comment by maxxfrazer** [comment]
@JetForMe looks like all those messages have gone away for me on the very recent release 3.4.6
