### ISSUE TITLE
How to create audio call on background or not running state?

### ISSUE THREAD

**Issue by shanmugam105** [AgoraIO/AgoraRtcEngine_iOS#32]
Currently, I'm facing the issue of connecting Agorasdk on the app's killed state. I have integrated the call kit through VoIP push notification. So, I can receive calls on the app killed state. But I don't know how to connect the AgoraSDK in the app's closed state. Any one help me?

**Comment by maxxfrazer** [comment]
Hey, please post support related issues in our support centre, the support team will get back to you there.

If you head to the console there should be a Support button at the top leading here: https://agora-ticket.agora.io/
