### ISSUE TITLE
Bluetooth headphones not working as expected

### ISSUE THREAD

**Issue by arifbd** [AgoraIO/AgoraRtcEngine_iOS#34]
### I have implemented `AgoraRtcEngine_iOS` one of my project for video calling. I am facing the below scenario.

Scenario:

1.   Bluetooth earphones connected
2.   Call comes to iPhone
3.   Ringtone plays on connected earphones
4.   After joining the agora channel no sounds on the connected earphone. Sounds are playing on the phone's speaker. I have `didAudioRouteChanged` function implemented. In this stage I get this result from SDK.

```
  didAudioRouteChanged -> AgoraAudioOutputRouting(rawValue: 5)
  didAudioRouteChanged -> AgoraAudioOutputRouting(rawValue: 3)
```
  5. Now call is ongoing, disconnect the connected earphones, and reconnect.
  In this stage, sounds are playing on connected earphones. and I get this result from SDK.
  `didAudioRouteChanged -> AgoraAudioOutputRouting(rawValue: 5)`
  
  <br/><br/>
  
  NB: I have tried this, but not worked.
  ```
agoraEngine.setAudioProfile(AudioProfile.default)
  agoraEngine.setAudioScenario(AudioScenario.gameStreaming)
```
  
<br/>

  **Please help me to solve this problem. I really appreciate any help you can provide.** :blush: :blush:

**Comment by maxxfrazer** [comment]
Hey @arifbd, I think the CS team might be able to help you with this one better. I mostly keep an eye out here for package integration issues.
If you head to the console there should be a Support button at the top leading here: https://agora-ticket.agora.io

If you create a ticket there, let me know the number and I'll keep an eye on it in our systems.

**Comment by maxxfrazer** [comment]
Going to close this issue now. Please make a support ticket with the link above if you haven't already.
