### ISSUE TITLE
[v4.1.1] rename `AgoraRtcChannelMediaOptions`.`publishTrancodedVideoTrack` to `publishTranscodedVideoTrack`

### ISSUE THREAD

**Issue by hawflakes** [AgoraIO/AgoraRtcEngine_iOS#36]
Looks to be a typo in `AgoraRtcChannelMediaOptions`.
`publishTrancodedVideoTrack` should be `publishTranscodedVideoTrack`

**Comment by maxxfrazer** [comment]
just spotted this is in the the latest SDK version, see API ref here:
https://agoraio.github.io/AgoraRtcEngine_iOS/documentation/agorartckit/agorartcchannelmediaoptions/publishtranscodedvideotrack
