### ISSUE TITLE
Audience side video streaming is not working in SDK 4.1.6

### ISSUE THREAD

**Issue by RabertD** [AgoraIO/AgoraRtcEngine_iOS#39]
While am upgrading my SDK to 4.1.6 from 3.7.0. Am getting below error
> Incorrect NSStringEncoding value 0x8000100 detected. Assuming NSASCIIStringEncoding. Will stop this compatibility mapping behavior in the near future

Also audience side video streaming is not working when we broadcast from native mobile app. Its working fine when broadcast from web
<img width="952" alt="Screenshot 2023-05-02 at 1 46 53 PM" src="https://user-images.githubusercontent.com/107385984/235615069-25f5a6de-4063-4f32-baf8-a925909a0522.png">

**Comment by maxxfrazer** [comment]
Hi @RabertD try follow the getting started guide and see if there's still the same issue there. Some things aren't clear such as when setClientRole or setChannelProfile are called.
Failing that, feel free to open an issue on the Support page, which can also be found on the console: https://agora-ticket.agora.io/

**Comment by RabertD** [comment]
setChannelProfile and setClientRole both are calling in the viewDidLoad

**Comment by RabertD** [comment]
Seems the problem was in simulator. but its working fine in real devices
