### ISSUE TITLE
修改原始錄音數據 耳返無效果

### ISSUE THREAD

**Issue by PengDai-ios** [AgoraIO/AgoraRtcEngine_iOS#4]
需求：用户唱歌的时候要加混响音效，耳返也要加上混响。

目前情况：修改录音原始数据后，送到远端的有混响音效效果。唱歌的人耳返没有效果。

修改数据时间点： onRecordAudioFrame 回调里面直接修改Buff数据

SDK版本号：3.1.1

**Comment by maxxfrazer** [comment]
你好，这个地方是为了整合问题。 请在此处制作支持票：
https://agora-ticket.agora.io/

en: Hello, this place is for integration issues.  Please make a support ticket here:
https://agora-ticket.agora.io/
