### ISSUE TITLE
While receiving call in production(in app store) does not appear but it does work in development(local)

### ISSUE THREAD

**Issue by priyathakkar1** [AgoraIO/AgoraRtcEngine_iOS#40]

**Comment by priyathakkar1** [comment]
By using this package, I have implemented a video call feature in my application but for the last few days, I have not received calls in the production server. Is there any change in the package?

**Comment by maxxfrazer** [comment]
I don't fully understand the issue - the package itself will not change in production vs building for release via Xcode. If it works with TestFlight and not on the App Store, it may be something with the release process of your app.

**Comment by maxxfrazer** [comment]
if there’s any more details you can provide, please open a ticket at: https://agora-ticket.agora.io/

**Comment by priyathakkar1** [comment]
Yes, there was something missing while releasing the application may be but its working fine now. Thank you.
