### ISSUE TITLE
AgoraAudioFrameDelegate not firing `onRecordAudioFrame:` (4.1.1)

### ISSUE THREAD

**Issue by fchauvin** [AgoraIO/AgoraRtcEngine_iOS#44]
We are attempting to access audio frames when using Agora, however this delegate function doesn't seem to be getting called.

We are correctly setting the delegate method, as true is returned from: `(BOOL)setAudioFrameDelegate:(id<AgoraAudioFrameDelegate> _Nullable)delegate`.

Some delegate methods are called as expected, such as `getObservedAudioFrame()` and `getRecordAudioParams()`,  however `onRecordAudioFrame` is never called.

**Comment by maxxfrazer** [comment]
Hope a ticket was opened at the right place, going to close this issue now.
