### ISSUE TITLE
we can't publish voice and get voice from other devices

### ISSUE THREAD

**Issue by milanpatoliya** [AgoraIO/AgoraRtcEngine_iOS#47]
objc[1250]: Class HWDarwinResamplerImpl is implemented in both /private/var/containers/Bundle/Application/FB9ED148-D29C-40C5-B15D-3C14D419AE52/Venting.app/Frameworks/AgoraSpatialAudioExtension.framework/AgoraSpatialAudioExtension (0x107aecd18) and /private/var/containers/Bundle/Application/FB9ED148-D29C-40C5-B15D-3C14D419AE52/Venting.app/Frameworks/AgoraAudioBeautyExtension.framework/AgoraAudioBeautyExtension (0x105659940). One of the two will be used. Which one is undefined.

**To Reproduce**
Happen when the app will run

**Expected behavior**
we can't publish voice and get voice from other devices 

SDK:- 4.1.1

Which is the latest voice call example?

**Comment by maxxfrazer** [comment]
Hi @milanpatoliya, there isn't enough information to help here. You can publish and receive voice with the SDK so long as the steps outlined in the docs are followed.
Try using the voice examples on API-Examples here: https://github.com/AgoraIO/API-Examples/tree/main/iOS/APIExample-Audio
