### ISSUE TITLE
[INTEGRATION] In React native , pod install sooooooo slow

### ISSUE THREAD

**Issue by iita71737** [AgoraIO/AgoraRtcEngine_iOS#48]
**Describe the bug**
![Screenshot 2023-08-10 at 1 12 57 PM](https://github.com/AgoraIO/AgoraRtcEngine_iOS/assets/11864209/f3475152-5355-4c00-9165-06a6d444599c)

In ReactNative 
Pod install is sooooo slow.

the SDK url : [HERE](https://download.agora.io/sdk/release/AgoraRtcEngine_iOS-4.2.0.zip)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacBook Pro Apple M1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by maxxfrazer** [comment]
it takes about 10 seconds for me, might be your connection speed?
Also this repo is specifically for the swift package install, you want to open a ticket instead, it’s listed s the other option when you click new ticket
