### ISSUE TITLE
v3.5.0.1 is incompatible with Swift Package Manager

### ISSUE THREAD

**Issue by brow** [AgoraIO/AgoraRtcEngine_iOS#5]
SPM’s [Version doc](https://developer.apple.com/documentation/swift_packages/version) says a package version needs to be “a three period-separated integer, for example 1.0.0". That implies that 3.5.0.1 is not a valid package version.

If I enter 3.5.0.1 as the minimum package version in Xcode, **Done** is grayed out:
![image](https://user-images.githubusercontent.com/238331/128765080-625d19ff-c9a9-4920-ba4f-edc488cfc9a7.png)

Xcode's **Swift Packages > Update to Latest Package Versions** also does not recognize the existence of v3.5.0.1. It resolves to v3.5.0 instead.

**Comment by maxxfrazer** [comment]
Thanks for letting us know @brow! I just tried and the best workaround would be selecting "Branch" instead and inserting "3.5.0.1" for this case. It's a bit annoying, so I apologise for that.
This update was an unexpected patch, so typically we don't use 4 integers like this. I'll relay to the team that we can't use versions like this so in the future any patch update should increment the last int (which is usually reserved for patches anyway)

**Comment by maxxfrazer** [comment]
I'll leave this issue open until 3.5.1 is released btw

**Comment by maxxfrazer** [comment]
@brow the latest version is another unexpected patch which can be fetched with `3.5.0-hotfix.2`, as this is a valid semantic version

**Comment by brow** [comment]
@maxxfrazer Thank you for adopting the new tag format and for returning to this thread to give me the heads-up about `3.5.0-hotfix.2`!

I confirmed that Xcode accepts `3.5.0-hotfix.2` as a valid `minimumVersion`.

**Comment by brow** [comment]
Actually, it turns out that if I set
```
requirement = {
    kind = upToNextMajorVersion;
    minimumVersion = "3.5.0-hotfix.2";
};
```
then SPM resolves the dependency to
```json
"state": {
  "branch": null,
  "revision": "b5e436255a97c2f3c4e9060cf72a7c81d640d2ea",
  "version": "3.5.0"
}
```
To get it to resolve to `3.5.0-hotfix.2`, I need to set
```
requirement = {
    kind = exactVersion;
    version = "3.5.0-hotfix.2";
};
```

**Comment by Rusik** [comment]
So what about this? We can't update from 3.5.0 to 3.5.0.3 because you are still using 4 digits instead of 3

**Comment by brow** [comment]
@Rusik @Barbatosso This should get you 3.5.0.3:
```
requirement = {
    kind = exactVersion;
    version = "3.5.0-r.3";
};
```
