### ISSUE TITLE
After running in Xcode 15, it crashes.

### ISSUE THREAD

**Issue by fangfangchen1207** [AgoraIO/AgoraRtcEngine_iOS#50]
The prompt message is 
Class HWDarwinResamplerImpl is implemented in both /private/var/containers/Bundle/Application/…/Frameworks/AgoraSpatialAudioExtension.framework/AgoraSpatialAudioExtension (0x10baa4e28) and /private/var/containers/Bundle/Application/…/Frameworks/AgoraAudioBeautyExtension.framework/AgoraAudioBeautyExtension (0x1096999a8). One of the two will be used. Which one is undefined.

There are more instances of duplicated classes compared to using 4.1.1.
After upgrading to version 4.2.2, this is the only one.

**Comment by maxxfrazer** [comment]
Hey @fangfangchen1207, this sounds like a bug. please make a ticket at the following link: https://agora-ticket.agora.io/

The issue process in GitHub should have that option for you.

**Comment by fangfangchen1207** [comment]
Understood! I've submitted the ticket and am eagerly anticipating a speedy resolution. Thank you!
