### ISSUE TITLE
[INTEGRATION]

### ISSUE THREAD

**Issue by baveku** [AgoraIO/AgoraRtcEngine_iOS#51]
**Describe the bug**
iOS Cannot receive stream message when using realtime transcription feature

**Expected behavior**
Receive Stream Message when enable Realtime Transcription Feature

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 17
 - Version 4.2.2

**Comment by maxxfrazer** [comment]
hi @baveku this sounds like a bug with the SDK or the setup for RTT you have. please make a ticket at the following link: https://agora-ticket.agora.io/
