### ISSUE TITLE
when I receive call using Voip notifications I cant get sender vioce and sender cant get my voice

### ISSUE THREAD

**Issue by milanpatoliya** [AgoraIO/AgoraRtcEngine_iOS#54]
**Describe the bug**
I have used Agora Audio SDK and then received a call when the application was open it works perfectly
when I receive calls using VoIP notifications I can't get the sender's voice and the sender can't get my

I don't get any error regarding this

**Video**

Working example

https://github.com/AgoraIO/AgoraRtcEngine_iOS/assets/44164918/efb94895-d4e9-4eae-93a8-50e260323856

Example of issue
https://github.com/AgoraIO/AgoraRtcEngine_iOS/assets/44164918/5b970b6b-67ab-4bb5-90cb-b0350d3d8481

 - Device: [e.g. iPhonexr, iPhone8]
 - OS: [e.g. 17.01]

**Comment by maxxfrazer** [comment]
I'd guess that you need to set roles to broadcaster on joining the VoIP channel? but this question would be better suited for the support team. follow the steps provided in making an issue on this repo to be directed to the support site.

<img width="938" alt="Screenshot 2023-12-08 at 15 58 34" src="https://github.com/AgoraIO/AgoraRtcEngine_iOS/assets/5754073/309a628f-f3a1-46eb-a74b-6d5a804218b7">

**Comment by milanpatoliya** [comment]
I cant get any solution

**Comment by bhav0010** [comment]
I am getting the same issue  but not find any solution . Can someone help me with this
