### ISSUE TITLE
How to import in Objective-C project

### ISSUE THREAD

**Issue by AndrewSB** [AgoraIO/AgoraRtcEngine_iOS#7]
Hey! i'm trying to depend on the swift package from an Objective-C target, i can build and run fine, but when i try to archive the project, i get an error saying 

i'm not sure what i'm doing wrong, in my Objective-C target i've tried to follow what you do in your iOS examples in my `.m` file:

<img width="947" alt="Screen Shot 2021-09-30 at 10 44 00 AM" src="https://user-images.githubusercontent.com/3814772/135504858-a28e1bf2-ec81-49a6-9f0c-faeaad3bc258.png">

i've tried changing my project settings, to no effect. I've set `SWIFT_INSTALL_OBJC_HEADER` to NO, and added a User Header search path of `"$(BUILD_ROOT)/../IntermediateBuildFilesPath/UninstalledProducts/include"`.

is this a problem you're aware of? do you have any idea how i might be including Agora incorrectly

**Comment by maxxfrazer** [comment]
I just opened up an old sample project that included this library and tried archiving, didn't have an issue there:
![Screenshot 2021-09-30 at 20 40 51](https://user-images.githubusercontent.com/5754073/135520102-d3d06f2b-4cfe-482f-abcb-7cffc397e170.png)

Please let me know what type of Mac device (Intel or M1), what version of the package, target OS version, Xcode version, and anything else that might help me reproduce the issue you're having.

In my screenshot I imported to the header file, but also tried adding the imports to the `.m` file and again had no issue archiving.

**Comment by AndrewSB** [comment]
i just tried a reduced example, and indeed it did seem to work. so its likely something with my .xcodeproj's flags

I'm using 3.5.0.2, targeting iOS 15 with Xcode 13. thanks for testing @maxxfrazer, i'll update here if i figure it out

**Comment by AndrewSB** [comment]
i ended up writing swift code instead, so this wasn't needed
